org: copremesis
app: aws-node-scheduled-cron
service: aws-node-scheduled-cron

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

functions:
  cronHandler:
    handler: handler.run
    events:
      - schedule: 
          rate: cron(*/5 * * * ? *)
          enabled: false
    environment:
      NAME:     ${env:NAME}
      IPSET_ID: ${env:IPSET_ID}
      SCOPE:    ${env:SCOPE}
      REGION:   ${env:REGION}
