org: copremesis
app: aws-python-scheduled-cron
service: aws-python-scheduled-cron

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.8

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(*/30 * * * ? *)
